config/routes.rb
Rails.application.routes.draw do
 resources :patients
 
 get "reports/index"
 get "reports/day_wise"
 get "reports/month_to_date"
 get "reports/month_wise"
 get "reports/day_wise_result"
 get "reports/month_to_date_result"
 get "reports/month_wise_result"

 devise_for :users
 root :to => 'patients#index'
   end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  validates :reading_value, presence: true
  scope :today_readings, ->{ where("date(created_at) = ?", Time.now.strftime("%Y-%m-%d").to_date)}
  scope :today_result, ->{ where("date(created_at) = ?", Time.now.to_date.strftime("%Y-%m-%d"))}
  scope :between_date, ->(begin_date, end_date){ where("date(created_at) between ? and ?",begin_date, end_date)}

  def self.check_count(user)
    result = user.patients.today_readings.count
    if result < 4
      return false
    else
      return true
    end
  end

  def self.day_wise(user)
    total = user.patients.today_result
    return [total.minimum(:reading_value).to_i, total.maximum(:reading_value).to_i, total.average(:reading_value).to_i]
  end

  def self.month_to_date_wise(user, params={})
    end_date = get_date(params["reading"])
    begin_date = end_date.beginning_of_month
    total = user.patients.between_date(begin_date,end_date)
    return [total.minimum(:reading_value).to_i, total.maximum(:reading_value).to_i, total.average(:reading_value).to_i]
  end

  def self.month_wise(user, params={})
    begin_date = get_date(params["reading"])
    end_date = begin_date.end_of_month
    total = user.patients.between_date(begin_date,end_date)
    return [total.minimum(:reading_value).to_i, total.maximum(:reading_value).to_i, total.average(:reading_value).to_i]
  end

  def self.get_date(reading_date)
    return Date.new(reading_date["created_at(1i)"].to_i,reading_date["created_at(2i)"].to_i,reading_date["created_at(3i)"].to_i)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :reading_count , :only => [:create]
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:user_id, :reading_value)
    end
    # check patient reading count
    def reading_count
        if Patient.check_count(current_user)
          redirect_to patients_url, notice: "Per day count four times only.You have reached limit already."
        end
      end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<div align='center'>
<%= form_for(patient) do |f| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reading_value %>
    <%= f.number_field :reading_value %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/patients/edit.html.erb
<div align='center'>
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>
</div>

app/views/patients/index.html.erb
<div align='center'>
<p id="notice"><%= notice %></p>

<h1>Patient Details</h1>

<table border="1">
  <thead>
    <tr>
      <th>Patient name</th>
      <th>Reading value</th>
      <th>Reading date</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= current_user.name %></td>
        <td align='center'><%= patient.reading_value %></td>
        <td><%= patient.created_at.strftime("%Y-%m-%d") %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>
<br>
<br>
<%= link_to 'Patient Reports', reports_index_path %>
</div>

app/views/patients/new.html.erb
<div align='center'>
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>
</div>

app/views/patients/show.html.erb
<div align='center'>
<p id="notice"><%= notice %></p>
<p>
  <strong>User name:</strong>
  <%= current_user.name %>
</p>

<p>
  <strong>Reading value:</strong>
  <%= @patient.reading_value %>
</p>
<p>
  <strong>Reading date:</strong>
  <%= @patient.created_at.strftime("%Y-%m-%d") %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>
</div>