config/routes.rb
Rails.application.routes.draw do
 resources :patients
 
 get "reports/index"
 get "reports/day_wise"
 get "reports/month_to_date"
 get "reports/month_wise"
 get "reports/day_wise_result"
 get "reports/month_to_date_result"
 get "reports/month_wise_result"

 devise_for :users
 root :to => 'patients#index'
   end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def day_wise_result
     @readings = Patient.day_wise(current_user)
   end

   def month_to_date_result
     @readings = Patient.month_to_date_wise(current_user,params)
   end

   def month_wise_result
     @readings = Patient.month_wise(current_user,params)
   end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<table border="1" align="center">
<thead>
<tr>
<th>Result Type</th>
<th>Reading Level</th>
</tr>
</thead>
<tbody>
<tr>
<td>Minimum</td>
<td align="center"><%= @readings[0]%></td>
</tr>
<tr>
<td>Maximum</td>
<td align="center"><%= @readings[1] %></td>
</tr>
<tr>
<td>Average</td>
<td align="center"><%= @readings[2]%></td>
</tr>
</tbody>
</table>
<br>
<div align="center"><%= link_to 'Back', reports_index_path %></div>

app/views/reports/day_wise.html.erb
<%= form_tag reports_day_wise_result_path, method: :get do %>
<label>Date Wise</label>
<%= date_select "reading","created_at", :disabled =>true %>
<%= submit_tag "Submit"%>
<% end %>

app/views/reports/day_wise_result.html.erb
<h2 align="center"><%= "Today Result" %></h2>
<%= render 'form' %>

app/views/reports/index.html.erb
<h1>Patients Reports</h1>
<table cellspacing="20">
<tr>
<td>
<%= link_to reports_day_wise_path  do %> <span>Daily Wise</span><%end%> </td>
<td>
<%= link_to reports_month_to_date_path do %> <span>Month to Date</span><%end%> </td>
<td>
<%= link_to reports_month_wise_path do %> <span>Month Wise</span><%end%> </td>
</tr>
</table>

app/views/reports/month_to_date.html.erb
<%= form_tag reports_month_to_date_result_path, method: :get do %>
<label>Month to date wise</label>
<%= date_select "reading","created_at"%>
<%= submit_tag "Submit"%>
<% end %>

app/views/reports/month_to_date_result.html.erb
<h2 align="center"><%= "Month to date wise Result" %></h2>
<%= render 'form' %>

app/views/reports/month_wise.html.erb
<%= form_tag reports_month_wise_result_path, method: :get do %>
<label>Month wise</label>
<%= date_select "reading","created_at",discard_day: true%>
<%= submit_tag "Submit"%>
<% end %>

app/views/reports/month_wise_result.html.erb
<h2 align="center"><%= "Month wise Result" %></h2>
<%= render 'form' %>